# Machine Learning Zoomcamp

1.7 - Introduction to NumPy

Plan:
- Creating arrays
- Multi-dimensional arrays
- Randomly generated arrays
- Element-wise operations
    - Comparison operations
    - Logical operations
- Summarizing operations

In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from 'C:\\Users\\Oximig01\\anaconda3\\Lib\\site-packages\\numpy\\__init__.py'>

# Creating arrays

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [8]:
a = np.array([1, 2, 4, 5, 7, 12])

In [10]:
a[2] = 23

In [11]:
a

array([ 1,  2, 23,  5,  7, 12])

In [12]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [16]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

# Multi-dimensional arrays

In [17]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [19]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
])

In [22]:
n[0]

array([1, 2, 3])

In [23]:
n[2, 0]

7

In [24]:
n[:, 1]

array([2, 5, 8])

In [26]:
n[:,1] = [9, 9, 2]

In [27]:
n

array([[1, 9, 3],
       [4, 9, 6],
       [7, 2, 9]])

# Randomly generated arrays

In [31]:
np.random.seed(23)
np.random.rand(5, 2)

array([[0.51729788, 0.9469626 ],
       [0.76545976, 0.28239584],
       [0.22104536, 0.68622209],
       [0.1671392 , 0.39244247],
       [0.61805235, 0.41193009]])

In [32]:
np.random.seed(23)
np.random.randn(5, 2) # normal distribution

array([[ 0.66698806,  0.02581308],
       [-0.77761941,  0.94863382],
       [ 0.70167179, -1.05108156],
       [-0.36754812, -1.13745969],
       [-1.32214752,  1.77225828]])

In [33]:
np.random.seed(23)
100 * np.random.rand(5, 2)

array([[51.72978838, 94.69626038],
       [76.54597594, 28.2395844 ],
       [22.10453633, 68.62220852],
       [16.71392031, 39.24424665],
       [61.80523473, 41.19300949]])

In [36]:
np.random.seed(23)
np.random.randint(low=0, high=100, size=(5, 2))

array([[83, 40],
       [73, 54],
       [31, 76],
       [91, 39],
       [90, 25]])

# Element-wise operations

In [38]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [39]:
a + 1

array([1, 2, 3, 4, 5])

In [44]:
b = (10 + (a * 2)) ** 2
b

array([100, 144, 196, 256, 324])

In [43]:
a + b

array([100, 145, 198, 259, 328])

# Comparsion operations

In [45]:
a >= 2

array([False, False,  True,  True,  True])

In [49]:
a > b/100

array([False, False,  True,  True,  True])

In [52]:
a[a > b/100] # retorna os elementos de a, em que a comparação é True

array([2, 3, 4])

# Summarizing operations

In [54]:
a

array([0, 1, 2, 3, 4])

In [53]:
a.min()

0

In [55]:
a.mean()

2.0

In [56]:
a.std()

1.4142135623730951

In [59]:
n.sum()

50