# Linear Algebra Refresher
- Vector operations
- Multiplication
    - Vector-vector multiplication
    - Matrix-vector multiplication
    - Matrix-matrix multiplication
- Identity matrix
- Inverse

# Vector operations

In [2]:
import numpy as np

In [3]:
u = np.array([2, 4, 5, 6])
v = np.array([1, 0, 0, 2])

In [5]:
u + v

array([3, 4, 5, 8])

In [6]:
u * v # resultado é diferente da áglebra de multiplicação das matrizes (deveria somar os valores, ao final)

array([ 2,  0,  0, 12])

# Multiplication

Vector-vector multiplication

In [10]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    result = 0.0
    
    for i in range(n):
        result = result + u[i] * v[i]
        
    return result

In [11]:
vector_vector_multiplication(u, v)

14.0

In [12]:
u.dot(v)

14

In [14]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1],
])

Matrix-vector multiplication

In [15]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]
    
    num_rows = U.shape[0]
    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
        
    return result

In [16]:
matrix_vector_multiplication(U, v)

array([14.,  5.,  5.])

In [17]:
U.dot(v)

array([14,  5,  5])

In [20]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1],
    [0, 2, 1],
    [2, 1, 0],
])

Matrix-matrix multiplication

In [21]:
def matrix_matrix_multiplication(U, v):
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi
        
    return result

In [25]:
matrix_matrix_multiplication(U, V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [24]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

# Identity matrix

In [27]:
I = np.eye(3)

In [29]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [28]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

# Matrix inverse

In [35]:
Vs = V[[0, 1, 2]] # precisa ser quadrada
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [37]:
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [39]:
Vs_inv.dot(Vs) # a multiplicação de uma matriz por sua inversa é a identidade

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])